General:
    Locale: en_US

    # Allow TfTAddon to report on basic anonymous usage
    Stats_Tracking: true

    # Allow TfTAddon to check if a new version is available
    Update_Check: true

    # Should TfTAddon print out debug messages?
    Verbose_Logging: false

    # Should TfTAddon over-write configs to update, or make new ones ending in .new?
    Config_Update_Overwrite: true

Skills:
    Axes:
      Durability_MaxBonusLevel: 100
      Durability_ChanceMax: 50
    Herbalism:
      SunnyDay_Cost: 30
      SunnyDay_UnlockLevel: 50
    Repair:
      BlacksmithsInstinct_UnlockLevel: 800
      BlacksmithsInstinct_WarnPercentage: 10.0
    Mining:
      SuperBreaker_InstantBreakObsidian: false

Announce_Level_Up:
    Power_Level: 1000
    Message_Range: 75.0

Prevent_Repair_Enchanted_Items:
    # When an item has an enchantment level higher than the maximum, repairing is cancelled.
    # Disable with 0 or -1
    Maximum_Enchantment_Level: 4
